# Package Tests

This notebook will make some tests to check if the package is working correctly. We will start by doing some simple TOML files to check if the package is able to read them correctly. Then we will move on to more complex tests.

To initialize any object in the package, you will need to create a TOML file with the configuration of the object you want to create. The package will read this file and create the object accordingly.

In [1]:
from src.core import runner as pyrsnc

runner_obj = pyrsnc.Runner(config_path="test.toml")

/home/keneth/Documents/Academic_Projects/Revision_Sismicidad_SGC/src/core/runner.py:61: UserWarning: No 'env_file' declared in [[databases]] profile 'sc6' of 'test.toml'. Reading credentials from the TOML entry and/or process environment. Avoid committing plaintext passwords to version control.
  self._dbm = DatabaseManager(self._cm)

At the initialization of the Runner object, the package will read the TOML file and create the object accordingly. If the TOML file is not found or is not valid, the package will raise an error. Let's start with a simple TOML file to check if the package is able to read it correctly. The TOML file will contain the configuration of a simple object that we will create.

Any TOML file must have at least the following info:
- A database provided
- A query to be executed on the database

```toml
[[database]]
name       = "sc6"
env_file   = ".env"  # It requires the .env file at the same path as the TOML file, otherwise specify the full path to the .env file
env_prefix = "SERVER_SC6"

[[queries]]
name       = "sc6"
sql_file   = "./queries/revision.sql"
description= "Query to retrieve events from SeisComP6 database"
database   = "sc6"
```

In [2]:
print(runner_obj.list_queries())

['sc6']

In [3]:
result = runner_obj.run()

In [4]:
result.total_events

,time_value,publicID,depth_value,magnitude_value,quality_standardError,depth_uncertainty,latitude_uncertainty,longitude_uncertainty,quality_associatedPhaseCount,quality_usedPhaseCount,...,quality_associatedStationCount,event_type,creationInfo_agencyID,text,latitude_value,longitude_value,magnitude_type,methodID,earthModelID,comment
0,2026-08-26 00:02:02+00:00,SGC2026qtbeit,10.000000,0.594362,1.953222,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"Dabeiba - Antioquia, Colombia",7.018000,-76.210000,MLr_1,,,None
1,2026-08-26 00:03:53+00:00,SGC2026qtbfyf,10.000000,-0.936168,13.431934,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"La Esperanza - Norte de Santander, Colombia",7.705400,-73.334400,MLr_vmm,,,None
2,2026-08-26 00:07:07+00:00,SGC2026qtbisr,10.000000,0.267247,0.807082,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"Dabeiba - Antioquia, Colombia",7.018000,-76.210000,MLr_1,,,None
3,2026-08-26 00:07:13+00:00,SGC2026qtbivf,12.260000,1.439425,0.310000,2.000000,1.909188,1.909188,11.0,11.0,...,NaN,earthquake,SGC,"Istmina - Chocó, Colombia",4.400667,-76.692833,MLr_1,Hypo71,RSNC,None
4,2026-08-26 00:07:29+00:00,SGC2026qtbjbe,162.800000,1.587182,0.200000,3.900000,4.101219,4.101219,8.0,8.0,...,NaN,earthquake,SGC,"Los Santos - Santander, Colombia",6.772333,-73.105667,MLr_3,Hypo71,RSNC,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2831,2026-09-03 21:20:00+00:00,SGC2026rjjiqk,10.000000,-0.066937,1.324995,NaN,NaN,NaN,NaN,NaN,...,NaN,not locatable,SGC,"Dabeiba - Antioquia, Colombia",7.018000,-76.210000,MLr_1,,,None
2832,2026-09-03 21:30:29+00:00,SGC2026rjjrrm,47.558594,3.167047,1.149697,5.051327,2.330371,2.028064,130.0,115.0,...,NaN,earthquake,SGC,"Sipí - Chocó, Colombia",4.475391,-76.667075,MLr_1,NonLinLoc,Poveda_et_al_2018,DESTACADO
2833,2026-09-03 22:30:26+00:00,SGC2026rjlriu,137.659040,2.214585,1.252237,6.601622,3.160192,5.848601,46.0,46.0,...,NaN,None,SGC,"Los Santos - Santander, Colombia",6.780796,-73.135931,MLr_3,NonLinLoc,Poveda_et_al_2018,None
2834,2026-09-03 23:15:14+00:00,SGC2026rjndyk,68.330566,4.765010,1.448835,22.273199,4.904731,4.548207,38.0,38.0,...,35.0,outside of network interest,SGC,Near Coast of Venezuela,10.318749,-62.438976,mb,LOCSAT,iasp91,None
2835,2026-09-03 23:32:39+00:00,SGC2026rjnsxz,42.013951,3.713323,0.834787,4.868501,2.278352,1.978237,92.0,92.0,...,NaN,earthquake,SGC,"Istmina - Chocó, Colombia",4.471161,-76.699024,MLr_1,NonLinLoc,Poveda_et_al_2018,DESTACADO

In [5]:
result.duplicates

Empty DataFrame
Columns: [time_value, publicID, depth_value, magnitude_value, quality_standardError, depth_uncertainty, latitude_uncertainty, longitude_uncertainty, quality_associatedPhaseCount, quality_usedPhaseCount, creationInfo_author, quality_usedStationCount, quality_associatedStationCount, event_type, creationInfo_agencyID, text, latitude_value, longitude_value, magnitude_type, methodID, earthModelID, comment]
Index: []

[0 rows x 22 columns]

In [6]:
result.checks

Empty DataFrame
Columns: [time_value, publicID, depth_value, magnitude_value, quality_standardError, depth_uncertainty, latitude_uncertainty, longitude_uncertainty, quality_associatedPhaseCount, quality_usedPhaseCount, creationInfo_author, quality_usedStationCount, quality_associatedStationCount, event_type, creationInfo_agencyID, text, latitude_value, longitude_value, magnitude_type, methodID, earthModelID, comment]
Index: []

[0 rows x 22 columns]

In [7]:
result.output

Empty DataFrame
Columns: [time_value, publicID, depth_value, magnitude_value, quality_standardError, depth_uncertainty, latitude_uncertainty, longitude_uncertainty, quality_associatedPhaseCount, quality_usedPhaseCount, creationInfo_author, quality_usedStationCount, quality_associatedStationCount, event_type, creationInfo_agencyID, text, latitude_value, longitude_value, magnitude_type, methodID, earthModelID, comment, Observations]
Index: []

[0 rows x 23 columns]

- The request using .env file is not reading correctly the variables.
- The duplicate search using sswa is not working, in adjacent method the table is not being filtered correctly and the observations are being added wrongly
- It is required to verify results with the previous seismic revision routine